# Generated by Django 5.1 on 2024-08-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_myuser_email_myuser_codemeli_myuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
