# Generated by Django 5.1 on 2024-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_myuser_first_name_remove_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
