# Generated by Django 5.1 on 2024-08-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_myuser_first_name_myuser_is_active_myuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
